### ISSUE TITLE
[question] - | ykfde | 1fa | config |

### ISSUE THREAD

**Issue by Falroi** [agherzan/yubikey-full-disk-encryption#82] opened 2021-05-17 23:09 UTC
I'm a little confused about the configuration of the 1FA bit. Is the "challenge" being set in ykfde.conf the actual secret key that was written to the yubikey in the HMAC-SHA1 Challenge-Response config step?

**Comment by Vincent43** [comment] 2021-05-18 16:35
No. The challenge is different than the secret written to yubikey. In order to retrieve yubikey response you need to combine them both:

challenge + secret key on yubikey = yubikey response

In 1fa mode they yubikey response is also the LUKS password.

The [readme](https://github.com/agherzan/yubikey-full-disk-encryption#automatic-mode-with-stored-challenge-1fa) states:

> The YubiKey response is a HMAC-SHA1 40 byte length string created from your provided challenge and 20 byte length secret key stored inside the token. It will be used as your LUKS encrypted volume passphrase.

**Comment by Falroi** [comment] 2021-05-18 16:50
Is the challenge just a phrase we make up though or is it something we need to generate?

**Comment by Vincent43** [comment] 2021-05-18 18:01
Users can set anything they want as challenge but it can't be longer than 64 characters. UEFI/BIOS shouldn't have any effect on usage of this project.

**Comment by Falroi** [comment] 2021-05-18 21:11
I'm going to try this again. Mind if we continue this dialogue to potentially help others that may come across any issues that I stumble upon? For anyone interested I am attempting this with Garuda, an arch based distro.

**Comment by Vincent43** [comment] 2021-05-18 21:44
> I am encrypting with luks at the time of installation via the garuda installer.

Did you enrolled ykfde compatible password with [ykfde-enroll](https://github.com/agherzan/yubikey-full-disk-encryption#enroll-ykfde-passphrase-to-existing-luks-encrypted-volume)?

**Comment by Falroi** [comment] 2021-05-18 22:26
> > I am encrypting with luks at the time of installation via the garuda installer.
> 
> 
> 
> Did you enrolled ykfde compatible password with [ykfde-enroll](https://github.com/agherzan/yubikey-full-disk-encryption#enroll-ykfde-passphrase-to-existing-luks-encrypted-volume) in post install?

The first time I tried using a password that was 7 digits and an * the second time I tried using two words with no space and a string of 7 digits with no space.

**Comment by Vincent43** [comment] 2021-05-19 08:57
> Update: I this could be hook related. I've just read that Garuda uses or has used plymouth by default. So at this point I'm going to try replacing the plymouth-encrypt hook with ykfde in mkinitcpio and regenerating.

Without ykfde hook there is no chance it could work.

> Update: No luck. It seems like it only wants to decrypt with keyslot 0 which is not the yubikey.

Is it ykfde doing the decrypt?  Can you confirm you have more than one keyslot used on device and ykfde password works when you try it on running system?

**Comment by Vincent43** [comment] 2021-05-19 11:16
Please ensure you have the right challenge written in /etc/ykfde.conf as `YKFDE_CHALLENGE="<challenge>"` then run `sudo ykfde-open -d /dev/<address> -t -v`.

**Comment by Falroi** [comment] 2021-05-20 07:17
> > Update: I this could be hook related. I've just read that Garuda uses or has used plymouth by default. So at this point I'm going to try replacing the plymouth-encrypt hook with ykfde in mkinitcpio and regenerating.
> 
> 
> 
> Without ykfde hook there is no chance it could work.
> 
> 
> 
> > Update: No luck. It seems like it only wants to decrypt with keyslot 0 which is not the yubikey.
> 
> 
> 
> Is it ykfde doing the decrypt?  Can you confirm you have more than one keyslot used on device and ykfde password works when you try it on running system?

As of now no, on boot its grub trying to handle the decrypt, and its asking for my passphrase using keyslot 0. Yes ykfde does work for both partitions on a running system I enrolled with ykfde.

**Comment by Falroi** [comment] 2021-05-20 07:18
> Please ensure you have the right challenge written in /etc/ykfde.conf as `YKFDE_CHALLENGE="<challenge>"` then run `sudo ykfde-open -d /dev/<address> -t -v -n test`.

Verified this and used the command posted, yubikey lights and unlocks the encrypted device with ykfde no problem. It looks like as of now my only issues are with booting only using the yubikey.

**Comment by Vincent43** [comment] 2021-05-20 09:10
grub is bootloader which only loads initramfs where encryption should happen unless you encrypt whole disk including `/boot`.

Could you post contents of `/etc/mkinitcpio.conf` ?

**Comment by Falroi** [comment] 2021-05-20 22:06
[mkinitcpio.conf](https://gist.github.com/Falroi/26af5e6835078ffc15c219cb108311a8)

**Comment by Vincent43** [comment] 2021-05-21 09:48
So as I understand you have `/boot` encrypted and you unlock disk at first by [grub cryptodisk](https://wiki.archlinux.org/title/GRUB#Encrypted_/boot) feature. For such scenario you can't utilize ykfde because grub isn't aware of it, see also https://github.com/agherzan/yubikey-full-disk-encryption/issues/33#issuecomment-418074107 .

Theoretically ykfde can work in second phase, inside initramfs to do second unlock (post-grub) but it supports only one encrypted partition while you have encrypted swap additionally.

**Comment by Vincent43** [comment] 2021-05-21 16:35
`/boot/efi`  is separate partition from` /boot`. EFI partition (in your case mounted in `/boot/efi`) can't be encrypted.

**Comment by Falroi** [comment] 2021-05-21 17:00
> `/boot/efi`  is separate partition from` /boot`. EFI partition (in your case mounted in `/boot/efi`) can't be encrypted.

Would you recommend I manually create the partitions on a fresh install? What would you do if it was your system?

**Comment by Vincent43** [comment] 2021-05-21 21:00
I made may recommendation before in https://github.com/agherzan/yubikey-full-disk-encryption/issues/33#issuecomment-418074107 . Instead of swap you may use [zram](https://wiki.archlinux.org/title/Improving_performance#Zram_or_zswap).

**Comment by Vincent43** [comment] 2021-05-25 14:17
Closing as duplicate of https://github.com/agherzan/yubikey-full-disk-encryption/issues/33 .

**Closed by Vincent43** 2021-05-25 14:17 UTC
